[build]
  command = "npm run build:netlify"
  publish = "dist/portifolio_with_angular/browser"

[context.production.environment]
  NODE_VERSION = "18.x"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
